from pathlib import Path
import json
import shutil

ROOT = Path(__file__).resolve().parent

APP = ROOT / "static" / "app.js"
OPS = ROOT / "static" / "ops_features.js"
EN = ROOT / "static" / "i18n" / "en.json"

# ------------------------------------------------------------
# 1. Backup
# ------------------------------------------------------------

for path, backup_name in [
    (APP, "app.before-remaining-i18n-fix.js"),
    (OPS, "ops_features.before-remaining-i18n-fix.js"),
    (EN, "en.before-remaining-i18n-fix.json"),
]:
    backup = path.parent / backup_name
    if not backup.exists():
        shutil.copy2(path, backup)

# ------------------------------------------------------------
# 2. English dictionary
# ------------------------------------------------------------

with EN.open("r", encoding="utf-8") as f:
    data = json.load(f)

translations = {
    # Admin -> Users
    "查看权限矩阵": "View Permission Matrix",

    # Operations Center
    "系统健康": "System Health",
    "设备利用率": "Equipment Utilization",
    "数据备份": "Database Backup",
    "通知中心": "Notification Center",
    "操作审计": "Audit Log",
    "通知": "Notifications",
    "云端运行": "Cloud Running",

    "峰值时段": "Peak Period",
    "共": "Total",
    "笔订单": "orders",
    "可用于容量与负荷预测的运营依据。":
        "Operational data that can support capacity and load forecasting.",

    "活跃用户": "Active Users",

    "电站利用率分析": "Station Utilization Analysis",
    "按近 28 天已完成订单的实际充电分钟数":
        "Calculated from actual charging minutes of completed orders in the past 28 days",
    "÷ 电桩可服务分钟数计算。":
        "divided by the available service minutes of charging piles.",

    "利用率 Top 5": "Top 5 by Utilization",
    "优先关注高负载站点。": "Prioritize high-load stations.",

    "用户行为": "User Behavior",
    "回访与消费概况。": "Returning-user and spending overview.",

    "人均订单": "Orders per User",
    "人均电量": "Energy per User",
    "人均消费": "Spending per User",
    "回访用户": "Returning Users",

    "24 小时使用分布": "24-Hour Usage Distribution",
    "订单量、电量和充电时长的时段分布。":
        "Hourly distribution of orders, energy, and charging duration.",

    "近 28 天订单": "Orders · Last 28 Days",
    "充电电量": "Charging Energy",
    "实收营收": "Collected Revenue",
    "平均利用率": "Average Utilization",

    # Notifications
    "通知中心": "Notification Center",
    "条未读通知": "unread notifications",
    "系统会根据当前业务状态自动生成提醒。":
        "The system automatically generates alerts based on current business conditions.",
    "全部已读": "Mark All as Read",
    "新": "New",
    "标记已读": "Mark as Read",
    "暂无通知": "No notifications",

    # Backup
    "数据库备份与恢复": "Database Backup & Recovery",
    "数据备份与恢复需要系统管理员权限。":
        "Database backup and recovery require system administrator privileges.",
    "当前角色无法执行数据库备份与恢复。":
        "The current role cannot perform database backup and recovery.",
    "当前数据库后端为": "The current database backend is",
    "本页面仅提供 SQLite 文件备份；":
        "This page only provides SQLite file backups;",
    "MySQL 请使用数据库原生备份。":
        "For MySQL, please use the database's native backup tools.",
    "创建 SQLite 热备并保留最近 10 份文件；":
        "Create a live SQLite backup and keep the latest 10 files;",
    "下载后可用于灾备恢复。":
        "Downloaded files can be used for disaster recovery.",
    "下载": "Download",
    "立即备份": "Back Up Now",
    "备份文件": "Backup File",
    "大小": "Size",
    "时间": "Time",
    "操作": "Action",

    # Audit log
    "支持按操作人、关键词和日期范围查询关键管理行为。":
        "Search key administrative actions by operator, keyword, and date range.",
    "暂无分类": "No categories",
    "搜索操作内容": "Search operation details",
    "操作人 ID": "Operator ID",
    "查询": "Search",
    "编号": "ID",
    "操作人": "Operator",
    "操作内容": "Operation",
    "查看增强审计日志需要相应的审计权限。":
        "Viewing enhanced audit logs requires the appropriate audit permission.",
    "无访问权限": "Access Denied",
    "当前角色无法查看增强审计日志。":
        "The current role cannot view enhanced audit logs.",
    "如需查看，请使用具有 audit.view 权限的运营人员或管理员账号。":
        "To view them, use an operator or administrator account with audit.view permission.",

    # Backup notification generated by backend
    "建议建立首个数据库备份": "Create Your First Database Backup",
    "当前还没有检测到数据库备份，建议先建立一份可恢复备份。":
        "No database backup has been detected yet. It is recommended to create a recoverable backup first.",

    # Technician dashboard
    "让每一台设备，都保持在最佳状态。":
        "Keep every device operating at its best.",
    "统一查看电站健康度、设备状态与异常情况，":
        "Monitor station health, equipment status, and exceptions in one place,",
    "直接从电站进入设备运维。":
        "and enter equipment operations directly from each station.",
    "设备": "Equipment",
}

# Add/update translations
for zh, en in translations.items():
    data[zh] = en

with EN.open("w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
    f.write("\n")

# ------------------------------------------------------------
# 3. Patch app.js
# ------------------------------------------------------------

app = APP.read_text(encoding="utf-8")

# The button is already tr("查看权限矩阵") in the current source,
# so adding the dictionary entry above is enough.
# This replacement is only a safety check.
app = app.replace(
    'pageBtn(\n                "roles",\n                "查看权限矩阵",',
    'pageBtn(\n                "roles",\n                tr("查看权限矩阵"),'
)

APP.write_text(app, encoding="utf-8")

# ------------------------------------------------------------
# 4. Patch ops_features.js
# ------------------------------------------------------------

ops = OPS.read_text(encoding="utf-8")

# Helper for translations inside this standalone module.
# It safely falls back to the original text if tr() is unavailable.
marker = "const opsTr ="
if marker not in ops:
    insert_after = "(() => {"
    if insert_after in ops:
        ops = ops.replace(
            insert_after,
            """(() => {

  const opsTr = (text) => {
    try {
      return typeof tr === 'function' ? tr(text) : text;
    } catch (_) {
      return text;
    }
  };
""",
            1,
        )

# ------------------------------------------------------------
# Operations Center banner
# ------------------------------------------------------------

ops = ops.replace(
    """系统健康 ·
                设备利用率 ·
                数据备份 ·
                通知中心 ·
                操作审计""",
    """${opsTr("系统健康")} ·
                ${opsTr("设备利用率")} ·
                ${opsTr("数据备份")} ·
                ${opsTr("通知中心")} ·
                ${opsTr("操作审计")}"""
)

ops = ops.replace(
    """<span>
                  通知
                </span>""",
    """<span>
                  ${opsTr("通知")}
                </span>"""
)

ops = ops.replace(
    """<span
                class="ops-pill success"
              >
                云端运行
              </span>""",
    """<span
                class="ops-pill success"
              >
                ${opsTr("云端运行")}
              </span>"""
)

# ------------------------------------------------------------
# Peak period
# ------------------------------------------------------------

ops = ops.replace(
    """<strong>
            峰值时段
            ${String(""",
    """<strong>
            ${opsTr("峰值时段")}
            ${String("""
)

ops = ops.replace(
    """<p>
            共
            ${peak.orders || 0}
            笔订单；
            可用于容量与负荷预测的运营依据。
          </p>""",
    """<p>
            ${opsTr("共")}
            ${peak.orders || 0}
            ${opsTr("笔订单")}；
            ${opsTr("可用于容量与负荷预测的运营依据。")}
          </p>"""
)

ops = ops.replace(
    """<span class="ops-pill">
          活跃用户
          ${ub.sessions_users || 0}
        </span>""",
    """<span class="ops-pill">
          ${opsTr("活跃用户")}
          ${ub.sessions_users || 0}
        </span>"""
)

# ------------------------------------------------------------
# Notifications
# ------------------------------------------------------------

ops = ops.replace(
    """<h2>
              通知中心
            </h2>""",
    """<h2>
              ${opsTr("通知中心")}
            </h2>"""
)

ops = ops.replace(
    """${d.unread || 0}
              条未读通知 ·
              系统会根据当前业务状态自动生成提醒。""",
    """${d.unread || 0}
              ${opsTr("条未读通知")} ·
              ${opsTr("系统会根据当前业务状态自动生成提醒。")}"""
)

ops = ops.replace(
    """            全部已读""",
    """            ${opsTr("全部已读")}"""
)

ops = ops.replace(
    """<span class="ops-unread">
                             新
                           </span>""",
    """<span class="ops-unread">
                             ${opsTr("新")}
                           </span>"""
)

ops = ops.replace(
    """                        标记已读""",
    """                        ${opsTr("标记已读")}"""
)

ops = ops.replace(
    """              暂无通知""",
    """              ${opsTr("暂无通知")}"""
)

# Translate dynamically generated notification title/body.
ops = ops.replace(
    """${esc0(
                      n.title
                    )}""",
    """${esc0(
                      opsTr(n.title)
                    )}"""
)

ops = ops.replace(
    """${esc0(
                      n.body
                    )}""",
    """${esc0(
                      opsTr(n.body)
                    )}"""
)

# ------------------------------------------------------------
# Backup section
# ------------------------------------------------------------

ops = ops.replace(
    "<h2>数据库备份与恢复</h2>",
    "<h2>${opsTr(\"数据库备份与恢复\")}</h2>"
)

ops = ops.replace(
    """数据备份与恢复需要系统管理员权限。""",
    """${opsTr("数据备份与恢复需要系统管理员权限。")}"""
)

ops = ops.replace(
    """            无访问权限""",
    """            ${opsTr("无访问权限")}"""
)

ops = ops.replace(
    """           当前角色无法执行数据库备份与恢复。""",
    """           ${opsTr("当前角色无法执行数据库备份与恢复。")}"""
)

ops = ops.replace(
    """<h2>
            数据备份
          </h2>""",
    """<h2>
            ${opsTr("数据备份")}
          </h2>"""
)

ops = ops.replace(
    """本页面仅提供 SQLite 文件备份；
            MySQL 请使用数据库原生备份。""",
    """${opsTr("本页面仅提供 SQLite 文件备份；")}
            ${opsTr("MySQL 请使用数据库原生备份。")}"""
)

ops = ops.replace(
    """<h2>
              数据库备份与恢复
            </h2>""",
    """<h2>
              ${opsTr("数据库备份与恢复")}
            </h2>"""
)

ops = ops.replace(
    """创建 SQLite 热备并保留最近 10 份文件；
              下载后可用于灾备恢复。""",
    """${opsTr("创建 SQLite 热备并保留最近 10 份文件；")}
              ${opsTr("下载后可用于灾备恢复。")}"""
)

ops = ops.replace(
    """            立即备份""",
    """            ${opsTr("立即备份")}"""
)

ops = ops.replace(
    """                下载""",
    """                ${opsTr("下载")}"""
)

# ------------------------------------------------------------
# Audit log section
# ------------------------------------------------------------

ops = ops.replace(
    """<h2>
              操作审计
            </h2>""",
    """<h2>
              ${opsTr("操作审计")}
            </h2>"""
)

ops = ops.replace(
    """<h2>操作审计</h2>""",
    """<h2>${opsTr("操作审计")}</h2>"""
)

ops = ops.replace(
    """支持按操作人、关键词和日期范围查询关键管理行为。""",
    """${opsTr("支持按操作人、关键词和日期范围查询关键管理行为。")}"""
)

ops = ops.replace(
    """'<span class="ops-mini">暂无分类</span>'""",
    """'<span class="ops-mini">' + opsTr("暂无分类") + '</span>'"""
)

ops = ops.replace(
    """placeholder="搜索操作内容" """,
    """placeholder="${opsTr("搜索操作内容")}" """
)

ops = ops.replace(
    """placeholder="操作人 ID" """,
    """placeholder="${opsTr("操作人 ID")}" """
)

ops = ops.replace(
    """            查询""",
    """            ${opsTr("查询")}"""
)

ops = ops.replace(
    """              '编号',
              '操作人',
              '操作内容',
              '时间'""",
    """              opsTr('编号'),
              opsTr('操作人'),
              opsTr('操作内容'),
              opsTr('时间')"""
)

ops = ops.replace(
    """               查看增强审计日志需要相应的审计权限。""",
    """               ${opsTr("查看增强审计日志需要相应的审计权限。")}"""
)

ops = ops.replace(
    """            无访问权限""",
    """            ${opsTr("无访问权限")}"""
)

ops = ops.replace(
    """           当前角色无法查看增强审计日志。""",
    """           ${opsTr("当前角色无法查看增强审计日志。")}"""
)

ops = ops.replace(
    """             如需查看，请使用具有 audit.view
             权限的运营人员或管理员账号。""",
    """             ${opsTr("如需查看，请使用具有 audit.view 权限的运营人员或管理员账号。")}"""
)

# ------------------------------------------------------------
# Write
# ------------------------------------------------------------

OPS.write_text(ops, encoding="utf-8")

print("Remaining i18n fixes applied.")
print()
print("Backups created:")
print("  static/app.before-remaining-i18n-fix.js")
print("  static/ops_features.before-remaining-i18n-fix.js")
print("  static/i18n/en.before-remaining-i18n-fix.json")